package com.stuloan.web.mybatis.domain.inte;

import com.stuloan.web.mybatis.domain.Creditscore;
import com.stuloan.web.mybatis.domain.Studentinfo;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface CreditscoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditscore
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditscore
     *
     * @mbggenerated
     */
    int insert(Creditscore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditscore
     *
     * @mbggenerated
     */
    int insertSelective(Creditscore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditscore
     *
     * @mbggenerated
     */
    Creditscore selectByPrimaryKey(String id);

    List<Creditscore> selectByParams(Map<String,Object> params);

    List<Map<String,Object>> selectByParams02(Map<String,Object> params);

    Integer selectCountByParams(Map<String,Object> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditscore
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Creditscore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditscore
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Creditscore record);
}