package com.stuloan.web.mybatis.domain.inte;

import com.stuloan.web.mybatis.domain.Creditmoney;
import com.stuloan.web.mybatis.domain.Stagefee;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository("creditmoneyMapper")
public interface CreditmoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditmoney
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditmoney
     *
     * @mbggenerated
     */
    int insert(Creditmoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditmoney
     *
     * @mbggenerated
     */
    int insertSelective(Creditmoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditmoney
     *
     * @mbggenerated
     */
    Creditmoney selectByPrimaryKey(String id);

    List<Creditmoney> selectByParams(Map<String,Object> params);

    Double selectloanmoneyByParams(Map<String,Object> params);

    Integer selectCountByParams(Map<String,Object> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditmoney
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Creditmoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditmoney
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Creditmoney record);
}