package com.stuloan.web.mybatis.domain.inte;

import com.stuloan.web.mybatis.domain.Loan;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository("loanMapper")
public interface LoanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int insert(Loan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int insertSelective(Loan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    Loan selectByPrimaryKey(String id);

    List<Loan> selectByParams(Map<String,Object> params);

    List<Map<String,Object>> selectByParams02(Map<String,Object> params);

    Integer selectCountByParams(Map<String,Object> params);
    List<Map<String,Object>> selectloanexpires(String searchdate);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Loan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Loan record);

    int updatebyorderno(String orderno);
}