package com.stuloan.web.mybatis.domain.inte;

import com.stuloan.web.mybatis.domain.Loanorder;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository("loanorderMapper")
public interface LoanorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbggenerated
     */
    int insert(Loanorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbggenerated
     */
    int insertSelective(Loanorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbggenerated
     */
    Loanorder selectByPrimaryKey(String id);

    List<Loanorder> selectByParams(Map<String, Object> params);

    Integer selectCountByParams(Map<String, Object> params);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Loanorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Loanorder record);

    List<Map<String,Object>> queryorder(Map<String, Object> params);

    int updatebyorderno(Loanorder record);

    Loanorder selectbyorderno(String orderno);
}