package com.stuloan.web.mybatis.domain.inte;

import com.stuloan.web.mybatis.domain.Repayorder;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository("repayorderMapper")
public interface RepayorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbggenerated
     */
    int insert(Repayorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbggenerated
     */
    int insertSelective(Repayorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbggenerated
     */
    Repayorder selectByPrimaryKey(String id);

    List<Repayorder> selectByParams(Map<String, Object> params);

    Integer selectCountByParams(Map<String, Object> params);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Repayorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Repayorder record);

    int updatebyorderno(Repayorder record);
}