package com.stuloan.web.mybatis.domain.inte;

import com.stuloan.web.mybatis.domain.Stagefee;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface StagefeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagefee
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagefee
     *
     * @mbggenerated
     */
    int insert(Stagefee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagefee
     *
     * @mbggenerated
     */
    int insertSelective(Stagefee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagefee
     *
     * @mbggenerated
     */
    Stagefee selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagefee
     *
     * @mbggenerated
     */

    List<Stagefee> selectByParams(Map<String,Object> params);

    Double selectfeeByage(String stagenum);

    Integer selectCountByParams(Map<String,Object> params);

    int updateByPrimaryKeySelective(Stagefee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagefee
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Stagefee record);
}