package com.stuloan.web.mybatis.domain.inte;

import com.stuloan.web.mybatis.domain.Studentinfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface StudentinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated
     */
    int insert(Studentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated
     */
    int insertSelective(Studentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated
     */
    Studentinfo selectByPrimaryKey(String id);

    List<Studentinfo> selectByParams(Studentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Studentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Studentinfo record);
}