package com.stuloan.web.mybatis.domain.inte;

import com.stuloan.web.mybatis.domain.Studentinfo;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface StudentinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated
     */
    int insert(Studentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated
     */
    int insertSelective(Studentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated
     */
    Studentinfo selectByPrimaryKey(String id);

    Studentinfo selectByuserid(String userid);

    List<Studentinfo> selectByParams(Studentinfo studentinfo);

    List<Map<String,Object>> selectByParams02(Map<String,Object> params);

    Integer selectCountByParams(Map<String,Object> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Studentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Studentinfo record);
}