package com.stuloan.web.mybatis.domain.inte;

import com.stuloan.web.mybatis.domain.Userphoto;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface UserphotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userphoto
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userphoto
     *
     * @mbggenerated
     */
    int insert(Userphoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userphoto
     *
     * @mbggenerated
     */
    int insertSelective(Userphoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userphoto
     *
     * @mbggenerated
     */
    Userphoto selectByPrimaryKey(String id);

    Userphoto selectByuserid(String userid);

    List<Map<String,Object>> selectByParams(Map<String,Object> params);
    Integer selectCountByParams(Map<String,Object> params);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userphoto
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userphoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userphoto
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Userphoto record);
}