package com.stuloan.web.mybatis.domain.inte;

import com.stuloan.web.mybatis.domain.Userresource;
import org.springframework.stereotype.Repository;

@Repository
public interface UserresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userresource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userresource
     *
     * @mbggenerated
     */
    int insert(Userresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userresource
     *
     * @mbggenerated
     */
    int insertSelective(Userresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userresource
     *
     * @mbggenerated
     */
    Userresource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userresource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userresource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Userresource record);
}