package com.stuloan.web.mybatis.domain;

import java.util.Date;

public class Blacklist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.overduecount
     *
     * @mbggenerated
     */
    private Integer overduecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.createid
     *
     * @mbggenerated
     */
    private String createid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.createname
     *
     * @mbggenerated
     */
    private String createname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blacklist.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbggenerated
     */
    public Blacklist(String id, String userid, Integer overduecount, Date createdate, String createid, String createname, String remark) {
        this.id = id;
        this.userid = userid;
        this.overduecount = overduecount;
        this.createdate = createdate;
        this.createid = createid;
        this.createname = createname;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blacklist
     *
     * @mbggenerated
     */
    public Blacklist() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.id
     *
     * @return the value of blacklist.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.id
     *
     * @param id the value for blacklist.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.userid
     *
     * @return the value of blacklist.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.userid
     *
     * @param userid the value for blacklist.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.overduecount
     *
     * @return the value of blacklist.overduecount
     *
     * @mbggenerated
     */
    public Integer getOverduecount() {
        return overduecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.overduecount
     *
     * @param overduecount the value for blacklist.overduecount
     *
     * @mbggenerated
     */
    public void setOverduecount(Integer overduecount) {
        this.overduecount = overduecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.createdate
     *
     * @return the value of blacklist.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.createdate
     *
     * @param createdate the value for blacklist.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.createid
     *
     * @return the value of blacklist.createid
     *
     * @mbggenerated
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.createid
     *
     * @param createid the value for blacklist.createid
     *
     * @mbggenerated
     */
    public void setCreateid(String createid) {
        this.createid = createid == null ? null : createid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.createname
     *
     * @return the value of blacklist.createname
     *
     * @mbggenerated
     */
    public String getCreatename() {
        return createname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.createname
     *
     * @param createname the value for blacklist.createname
     *
     * @mbggenerated
     */
    public void setCreatename(String createname) {
        this.createname = createname == null ? null : createname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blacklist.remark
     *
     * @return the value of blacklist.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blacklist.remark
     *
     * @param remark the value for blacklist.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}