package com.stuloan.web.mybatis.domain;


public class Creditmoney {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditmoney.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditmoney.creditlevel
     *
     * @mbggenerated
     */
    private Integer creditlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditmoney.thresholdscore
     *
     * @mbggenerated
     */
    private Double thresholdscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditmoney.loanmoney
     *
     * @mbggenerated
     */
    private Double loanmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditmoney.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditmoney
     *
     * @mbggenerated
     */
    public Creditmoney(String id, Integer creditlevel, Double thresholdscore, Double loanmoney, String remark) {
        this.id = id;
        this.creditlevel = creditlevel;
        this.thresholdscore = thresholdscore;
        this.loanmoney = loanmoney;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditmoney
     *
     * @mbggenerated
     */
    public Creditmoney() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditmoney.id
     *
     * @return the value of creditmoney.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditmoney.id
     *
     * @param id the value for creditmoney.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditmoney.creditlevel
     *
     * @return the value of creditmoney.creditlevel
     *
     * @mbggenerated
     */
    public Integer getCreditlevel() {
        return creditlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditmoney.creditlevel
     *
     * @param creditlevel the value for creditmoney.creditlevel
     *
     * @mbggenerated
     */
    public void setCreditlevel(Integer creditlevel) {
        this.creditlevel = creditlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditmoney.thresholdscore
     *
     * @return the value of creditmoney.thresholdscore
     *
     * @mbggenerated
     */
    public Double getThresholdscore() {
        return thresholdscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditmoney.thresholdscore
     *
     * @param thresholdscore the value for creditmoney.thresholdscore
     *
     * @mbggenerated
     */
    public void setThresholdscore(Double thresholdscore) {
        this.thresholdscore = thresholdscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditmoney.loanmoney
     *
     * @return the value of creditmoney.loanmoney
     *
     * @mbggenerated
     */
    public Double getLoanmoney() {
        return loanmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditmoney.loanmoney
     *
     * @param loanmoney the value for creditmoney.loanmoney
     *
     * @mbggenerated
     */
    public void setLoanmoney(Double loanmoney) {
        this.loanmoney = loanmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column creditmoney.remark
     *
     * @return the value of creditmoney.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column creditmoney.remark
     *
     * @param remark the value for creditmoney.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}