package com.stuloan.web.mybatis.domain;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.sourcecode
     *
     * @mbggenerated
     */
    private String sourcecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.sourcename
     *
     * @mbggenerated
     */
    private String sourcename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.sourcedesc
     *
     * @mbggenerated
     */
    private String sourcedesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.sourcelevel
     *
     * @mbggenerated
     */
    private Integer sourcelevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.sourcetype
     *
     * @mbggenerated
     */
    private Integer sourcetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.sourceurl
     *
     * @mbggenerated
     */
    private String sourceurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.parentsourceid
     *
     * @mbggenerated
     */
    private Integer parentsourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.parentsourcecode
     *
     * @mbggenerated
     */
    private String parentsourcecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated
     */
    public Resource(String id, String sourcecode, String sourcename, String sourcedesc, Integer sourcelevel, Integer sourcetype, String sourceurl, Integer parentsourceid, String parentsourcecode, Integer state) {
        this.id = id;
        this.sourcecode = sourcecode;
        this.sourcename = sourcename;
        this.sourcedesc = sourcedesc;
        this.sourcelevel = sourcelevel;
        this.sourcetype = sourcetype;
        this.sourceurl = sourceurl;
        this.parentsourceid = parentsourceid;
        this.parentsourcecode = parentsourcecode;
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated
     */
    public Resource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.sourcecode
     *
     * @return the value of resource.sourcecode
     *
     * @mbggenerated
     */
    public String getSourcecode() {
        return sourcecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.sourcecode
     *
     * @param sourcecode the value for resource.sourcecode
     *
     * @mbggenerated
     */
    public void setSourcecode(String sourcecode) {
        this.sourcecode = sourcecode == null ? null : sourcecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.sourcename
     *
     * @return the value of resource.sourcename
     *
     * @mbggenerated
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.sourcename
     *
     * @param sourcename the value for resource.sourcename
     *
     * @mbggenerated
     */
    public void setSourcename(String sourcename) {
        this.sourcename = sourcename == null ? null : sourcename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.sourcedesc
     *
     * @return the value of resource.sourcedesc
     *
     * @mbggenerated
     */
    public String getSourcedesc() {
        return sourcedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.sourcedesc
     *
     * @param sourcedesc the value for resource.sourcedesc
     *
     * @mbggenerated
     */
    public void setSourcedesc(String sourcedesc) {
        this.sourcedesc = sourcedesc == null ? null : sourcedesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.sourcelevel
     *
     * @return the value of resource.sourcelevel
     *
     * @mbggenerated
     */
    public Integer getSourcelevel() {
        return sourcelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.sourcelevel
     *
     * @param sourcelevel the value for resource.sourcelevel
     *
     * @mbggenerated
     */
    public void setSourcelevel(Integer sourcelevel) {
        this.sourcelevel = sourcelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.sourcetype
     *
     * @return the value of resource.sourcetype
     *
     * @mbggenerated
     */
    public Integer getSourcetype() {
        return sourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.sourcetype
     *
     * @param sourcetype the value for resource.sourcetype
     *
     * @mbggenerated
     */
    public void setSourcetype(Integer sourcetype) {
        this.sourcetype = sourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.sourceurl
     *
     * @return the value of resource.sourceurl
     *
     * @mbggenerated
     */
    public String getSourceurl() {
        return sourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.sourceurl
     *
     * @param sourceurl the value for resource.sourceurl
     *
     * @mbggenerated
     */
    public void setSourceurl(String sourceurl) {
        this.sourceurl = sourceurl == null ? null : sourceurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.parentsourceid
     *
     * @return the value of resource.parentsourceid
     *
     * @mbggenerated
     */
    public Integer getParentsourceid() {
        return parentsourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.parentsourceid
     *
     * @param parentsourceid the value for resource.parentsourceid
     *
     * @mbggenerated
     */
    public void setParentsourceid(Integer parentsourceid) {
        this.parentsourceid = parentsourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.parentsourcecode
     *
     * @return the value of resource.parentsourcecode
     *
     * @mbggenerated
     */
    public String getParentsourcecode() {
        return parentsourcecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.parentsourcecode
     *
     * @param parentsourcecode the value for resource.parentsourcecode
     *
     * @mbggenerated
     */
    public void setParentsourcecode(String parentsourcecode) {
        this.parentsourcecode = parentsourcecode == null ? null : parentsourcecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.state
     *
     * @return the value of resource.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.state
     *
     * @param state the value for resource.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }
}