package com.stuloan.web.mybatis.domain;

import java.util.Date;

public class Shortmessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shortmessage.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shortmessage.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shortmessage.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shortmessage.msgcontent
     *
     * @mbggenerated
     */
    private String msgcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shortmessage.msgdate
     *
     * @mbggenerated
     */
    private Date msgdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shortmessage.issend
     *
     * @mbggenerated
     */
    private String issend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shortmessage.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortmessage
     *
     * @mbggenerated
     */
    public Shortmessage(String id, String userid, String phone, String msgcontent, Date msgdate, String issend, String remark) {
        this.id = id;
        this.userid = userid;
        this.phone = phone;
        this.msgcontent = msgcontent;
        this.msgdate = msgdate;
        this.issend = issend;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortmessage
     *
     * @mbggenerated
     */
    public Shortmessage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shortmessage.id
     *
     * @return the value of shortmessage.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shortmessage.id
     *
     * @param id the value for shortmessage.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shortmessage.userid
     *
     * @return the value of shortmessage.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shortmessage.userid
     *
     * @param userid the value for shortmessage.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shortmessage.phone
     *
     * @return the value of shortmessage.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shortmessage.phone
     *
     * @param phone the value for shortmessage.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shortmessage.msgcontent
     *
     * @return the value of shortmessage.msgcontent
     *
     * @mbggenerated
     */
    public String getMsgcontent() {
        return msgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shortmessage.msgcontent
     *
     * @param msgcontent the value for shortmessage.msgcontent
     *
     * @mbggenerated
     */
    public void setMsgcontent(String msgcontent) {
        this.msgcontent = msgcontent == null ? null : msgcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shortmessage.msgdate
     *
     * @return the value of shortmessage.msgdate
     *
     * @mbggenerated
     */
    public Date getMsgdate() {
        return msgdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shortmessage.msgdate
     *
     * @param msgdate the value for shortmessage.msgdate
     *
     * @mbggenerated
     */
    public void setMsgdate(Date msgdate) {
        this.msgdate = msgdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shortmessage.issend
     *
     * @return the value of shortmessage.issend
     *
     * @mbggenerated
     */
    public String getIssend() {
        return issend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shortmessage.issend
     *
     * @param issend the value for shortmessage.issend
     *
     * @mbggenerated
     */
    public void setIssend(String issend) {
        this.issend = issend == null ? null : issend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shortmessage.remark
     *
     * @return the value of shortmessage.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shortmessage.remark
     *
     * @param remark the value for shortmessage.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}