package com.stuloan.web.mybatis.domain;

import java.util.Date;

public class Sms {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.smstype
     *
     * @mbggenerated
     */
    private String smstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.smsphone
     *
     * @mbggenerated
     */
    private String smsphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.smscode
     *
     * @mbggenerated
     */
    private String smscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.smscontent
     *
     * @mbggenerated
     */
    private String smscontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.smstime
     *
     * @mbggenerated
     */
    private Date smstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.validtime
     *
     * @mbggenerated
     */
    private Date validtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.smsdesc
     *
     * @mbggenerated
     */
    private String smsdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.signname
     *
     * @mbggenerated
     */
    private String signname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.templatecode
     *
     * @mbggenerated
     */
    private String templatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms.templateparam
     *
     * @mbggenerated
     */
    private String templateparam;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated
     */
    public Sms(String id, String smstype, String smsphone, String smscode, String smscontent, Date smstime, Date validtime, String state, String smsdesc, String remark, String signname, String templatecode, String templateparam) {
        this.id = id;
        this.smstype = smstype;
        this.smsphone = smsphone;
        this.smscode = smscode;
        this.smscontent = smscontent;
        this.smstime = smstime;
        this.validtime = validtime;
        this.state = state;
        this.smsdesc = smsdesc;
        this.remark = remark;
        this.signname = signname;
        this.templatecode = templatecode;
        this.templateparam = templateparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms
     *
     * @mbggenerated
     */
    public Sms() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.id
     *
     * @return the value of sms.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.id
     *
     * @param id the value for sms.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.smstype
     *
     * @return the value of sms.smstype
     *
     * @mbggenerated
     */
    public String getSmstype() {
        return smstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.smstype
     *
     * @param smstype the value for sms.smstype
     *
     * @mbggenerated
     */
    public void setSmstype(String smstype) {
        this.smstype = smstype == null ? null : smstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.smsphone
     *
     * @return the value of sms.smsphone
     *
     * @mbggenerated
     */
    public String getSmsphone() {
        return smsphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.smsphone
     *
     * @param smsphone the value for sms.smsphone
     *
     * @mbggenerated
     */
    public void setSmsphone(String smsphone) {
        this.smsphone = smsphone == null ? null : smsphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.smscode
     *
     * @return the value of sms.smscode
     *
     * @mbggenerated
     */
    public String getSmscode() {
        return smscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.smscode
     *
     * @param smscode the value for sms.smscode
     *
     * @mbggenerated
     */
    public void setSmscode(String smscode) {
        this.smscode = smscode == null ? null : smscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.smscontent
     *
     * @return the value of sms.smscontent
     *
     * @mbggenerated
     */
    public String getSmscontent() {
        return smscontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.smscontent
     *
     * @param smscontent the value for sms.smscontent
     *
     * @mbggenerated
     */
    public void setSmscontent(String smscontent) {
        this.smscontent = smscontent == null ? null : smscontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.smstime
     *
     * @return the value of sms.smstime
     *
     * @mbggenerated
     */
    public Date getSmstime() {
        return smstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.smstime
     *
     * @param smstime the value for sms.smstime
     *
     * @mbggenerated
     */
    public void setSmstime(Date smstime) {
        this.smstime = smstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.validtime
     *
     * @return the value of sms.validtime
     *
     * @mbggenerated
     */
    public Date getValidtime() {
        return validtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.validtime
     *
     * @param validtime the value for sms.validtime
     *
     * @mbggenerated
     */
    public void setValidtime(Date validtime) {
        this.validtime = validtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.state
     *
     * @return the value of sms.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.state
     *
     * @param state the value for sms.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.smsdesc
     *
     * @return the value of sms.smsdesc
     *
     * @mbggenerated
     */
    public String getSmsdesc() {
        return smsdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.smsdesc
     *
     * @param smsdesc the value for sms.smsdesc
     *
     * @mbggenerated
     */
    public void setSmsdesc(String smsdesc) {
        this.smsdesc = smsdesc == null ? null : smsdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.remark
     *
     * @return the value of sms.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.remark
     *
     * @param remark the value for sms.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.signname
     *
     * @return the value of sms.signname
     *
     * @mbggenerated
     */
    public String getSignname() {
        return signname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.signname
     *
     * @param signname the value for sms.signname
     *
     * @mbggenerated
     */
    public void setSignname(String signname) {
        this.signname = signname == null ? null : signname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.templatecode
     *
     * @return the value of sms.templatecode
     *
     * @mbggenerated
     */
    public String getTemplatecode() {
        return templatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.templatecode
     *
     * @param templatecode the value for sms.templatecode
     *
     * @mbggenerated
     */
    public void setTemplatecode(String templatecode) {
        this.templatecode = templatecode == null ? null : templatecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms.templateparam
     *
     * @return the value of sms.templateparam
     *
     * @mbggenerated
     */
    public String getTemplateparam() {
        return templateparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms.templateparam
     *
     * @param templateparam the value for sms.templateparam
     *
     * @mbggenerated
     */
    public void setTemplateparam(String templateparam) {
        this.templateparam = templateparam == null ? null : templateparam.trim();
    }
}