package com.stuloan.web.mybatis.domain;


public class Stagefee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stagefee.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stagefee.stagenum
     *
     * @mbggenerated
     */
    private Integer stagenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stagefee.feepercent
     *
     * @mbggenerated
     */
    private Double feepercent;

    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stagefee.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagefee
     *
     * @mbggenerated
     */
    public Stagefee(String id, Integer stagenum, Double feepercent, String state, String remark) {
        this.id = id;
        this.stagenum = stagenum;
        this.feepercent = feepercent;
        this.state = state;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stagefee
     *
     * @mbggenerated
     */
    public Stagefee() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stagefee.id
     *
     * @return the value of stagefee.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stagefee.id
     *
     * @param id the value for stagefee.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stagefee.stagenum
     *
     * @return the value of stagefee.stagenum
     *
     * @mbggenerated
     */
    public Integer getStagenum() {
        return stagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stagefee.stagenum
     *
     * @param stagenum the value for stagefee.stagenum
     *
     * @mbggenerated
     */
    public void setStagenum(Integer stagenum) {
        this.stagenum = stagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stagefee.feepercent
     *
     * @return the value of stagefee.feepercent
     *
     * @mbggenerated
     */
    public Double getFeepercent() {
        return feepercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stagefee.feepercent
     *
     * @param feepercent the value for stagefee.feepercent
     *
     * @mbggenerated
     */
    public void setFeepercent(Double feepercent) {
        this.feepercent = feepercent;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stagefee.remark
     *
     * @return the value of stagefee.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stagefee.remark
     *
     * @param remark the value for stagefee.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}