package com.stuloan.web.mybatis.domain;

public class Sysuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.loginname
     *
     * @mbggenerated
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.idcard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wechart
     *
     * @mbggenerated
     */
    private String wechart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qqnum
     *
     * @mbggenerated
     */
    private String qqnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createman
     *
     * @mbggenerated
     */
    private String createman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createdate
     *
     * @mbggenerated
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.district
     *
     * @mbggenerated
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.county
     *
     * @mbggenerated
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.town
     *
     * @mbggenerated
     */
    private String town;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.detailaddr
     *
     * @mbggenerated
     */
    private String detailaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userphoto
     *
     * @mbggenerated
     */
    private String userphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.idcardphoto
     *
     * @mbggenerated
     */
    private String idcardphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isconsole
     *
     * @mbggenerated
     */
    private Integer isconsole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isfront
     *
     * @mbggenerated
     */
    private Integer isfront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userfrom
     *
     * @mbggenerated
     */
    private Integer userfrom;

    private String isstuidentity;

    private Double loanlimit;

    private String iscreditidentity;

    private String isfrozen;

    private String photostate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public Sysuser(String id, String username, String loginname, String password, String idcard, String phone
            , String wechart, String qqnum, String remark, String createman, String createdate, String province
            , String city, String district, String county, String town, String detailaddr, String userphoto
            , String idcardphoto, Integer state, Integer isconsole, Integer isfront, Integer userfrom
            , String isstuidentity, Double loanlimit, String iscreditidentity, String isfrozen, String photostate) {
        this.id = id;
        this.username = username;
        this.loginname = loginname;
        this.password = password;
        this.idcard = idcard;
        this.phone = phone;
        this.wechart = wechart;
        this.qqnum = qqnum;
        this.remark = remark;
        this.createman = createman;
        this.createdate = createdate;
        this.province = province;
        this.city = city;
        this.district = district;
        this.county = county;
        this.town = town;
        this.detailaddr = detailaddr;
        this.userphoto = userphoto;
        this.idcardphoto = idcardphoto;
        this.state = state;
        this.isconsole = isconsole;
        this.isfront = isfront;
        this.userfrom = userfrom;
        this.isstuidentity = isstuidentity;
        this.loanlimit = loanlimit;
        this.iscreditidentity = iscreditidentity;
        this.isfrozen = isfrozen;
        this.photostate = photostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public Sysuser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.loginname
     *
     * @return the value of user.loginname
     *
     * @mbggenerated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.loginname
     *
     * @param loginname the value for user.loginname
     *
     * @mbggenerated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.idcard
     *
     * @return the value of user.idcard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.idcard
     *
     * @param idcard the value for user.idcard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wechart
     *
     * @return the value of user.wechart
     *
     * @mbggenerated
     */
    public String getWechart() {
        return wechart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wechart
     *
     * @param wechart the value for user.wechart
     *
     * @mbggenerated
     */
    public void setWechart(String wechart) {
        this.wechart = wechart == null ? null : wechart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qqnum
     *
     * @return the value of user.qqnum
     *
     * @mbggenerated
     */
    public String getQqnum() {
        return qqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qqnum
     *
     * @param qqnum the value for user.qqnum
     *
     * @mbggenerated
     */
    public void setQqnum(String qqnum) {
        this.qqnum = qqnum == null ? null : qqnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.remark
     *
     * @return the value of user.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.remark
     *
     * @param remark the value for user.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createman
     *
     * @return the value of user.createman
     *
     * @mbggenerated
     */
    public String getCreateman() {
        return createman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createman
     *
     * @param createman the value for user.createman
     *
     * @mbggenerated
     */
    public void setCreateman(String createman) {
        this.createman = createman == null ? null : createman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createdate
     *
     * @return the value of user.createdate
     *
     * @mbggenerated
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createdate
     *
     * @param createdate the value for user.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.province
     *
     * @return the value of user.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.province
     *
     * @param province the value for user.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.district
     *
     * @return the value of user.district
     *
     * @mbggenerated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.district
     *
     * @param district the value for user.district
     *
     * @mbggenerated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.county
     *
     * @return the value of user.county
     *
     * @mbggenerated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.county
     *
     * @param county the value for user.county
     *
     * @mbggenerated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.town
     *
     * @return the value of user.town
     *
     * @mbggenerated
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.town
     *
     * @param town the value for user.town
     *
     * @mbggenerated
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.detailaddr
     *
     * @return the value of user.detailaddr
     *
     * @mbggenerated
     */
    public String getDetailaddr() {
        return detailaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.detailaddr
     *
     * @param detailaddr the value for user.detailaddr
     *
     * @mbggenerated
     */
    public void setDetailaddr(String detailaddr) {
        this.detailaddr = detailaddr == null ? null : detailaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userphoto
     *
     * @return the value of user.userphoto
     *
     * @mbggenerated
     */
    public String getUserphoto() {
        return userphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userphoto
     *
     * @param userphoto the value for user.userphoto
     *
     * @mbggenerated
     */
    public void setUserphoto(String userphoto) {
        this.userphoto = userphoto == null ? null : userphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.idcardphoto
     *
     * @return the value of user.idcardphoto
     *
     * @mbggenerated
     */
    public String getIdcardphoto() {
        return idcardphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.idcardphoto
     *
     * @param idcardphoto the value for user.idcardphoto
     *
     * @mbggenerated
     */
    public void setIdcardphoto(String idcardphoto) {
        this.idcardphoto = idcardphoto == null ? null : idcardphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.state
     *
     * @return the value of user.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.state
     *
     * @param state the value for user.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isconsole
     *
     * @return the value of user.isconsole
     *
     * @mbggenerated
     */
    public Integer getIsconsole() {
        return isconsole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isconsole
     *
     * @param isconsole the value for user.isconsole
     *
     * @mbggenerated
     */
    public void setIsconsole(Integer isconsole) {
        this.isconsole = isconsole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isfront
     *
     * @return the value of user.isfront
     *
     * @mbggenerated
     */
    public Integer getIsfront() {
        return isfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isfront
     *
     * @param isfront the value for user.isfront
     *
     * @mbggenerated
     */
    public void setIsfront(Integer isfront) {
        this.isfront = isfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userfrom
     *
     * @return the value of user.userfrom
     *
     * @mbggenerated
     */
    public Integer getUserfrom() {
        return userfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userfrom
     *
     * @param userfrom the value for user.userfrom
     *
     * @mbggenerated
     */
    public void setUserfrom(Integer userfrom) {
        this.userfrom = userfrom;
    }

    public String getIsstuidentity() {
        return isstuidentity;
    }

    public void setIsstuidentity(String isstuidentity) {
        this.isstuidentity = isstuidentity;
    }

    public Double getLoanlimit() {
        return loanlimit;
    }

    public void setLoanlimit(Double loanlimit) {
        this.loanlimit = loanlimit;
    }

    public String getIscreditidentity() {
        return iscreditidentity;
    }

    public void setIscreditidentity(String iscreditidentity) {
        this.iscreditidentity = iscreditidentity;
    }

    public String getIsfrozen() {
        return isfrozen;
    }

    public void setIsfrozen(String isfrozen) {
        this.isfrozen = isfrozen;
    }

    public String getPhotostate() {
        return photostate;
    }

    public void setPhotostate(String photostate) {
        this.photostate = photostate;
    }
}