package com.stuloan.web.mybatis.domain;

public class Userphoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userphoto.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userphoto.userid
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userphoto.headphoto
     *
     * @mbggenerated
     */
    private String headphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userphoto.headstate
     *
     * @mbggenerated
     */
    private String headstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userphoto.idcardphoto
     *
     * @mbggenerated
     */
    private String idcardphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userphoto.idcardstate
     *
     * @mbggenerated
     */
    private String idcardstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userphoto.stuidcardphoto
     *
     * @mbggenerated
     */
    private String stuidcardphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userphoto.stuidcardstate
     *
     * @mbggenerated
     */
    private String stuidcardstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userphoto.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userphoto
     *
     * @mbggenerated
     */
    public Userphoto(String id, String userid, String headphoto, String headstate, String idcardphoto, String idcardstate, String stuidcardphoto, String stuidcardstate, String remark) {
        this.id = id;
        this.userid = userid;
        this.headphoto = headphoto;
        this.headstate = headstate;
        this.idcardphoto = idcardphoto;
        this.idcardstate = idcardstate;
        this.stuidcardphoto = stuidcardphoto;
        this.stuidcardstate = stuidcardstate;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userphoto
     *
     * @mbggenerated
     */
    public Userphoto() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userphoto.id
     *
     * @return the value of userphoto.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userphoto.id
     *
     * @param id the value for userphoto.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userphoto.userid
     *
     * @return the value of userphoto.userid
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userphoto.userid
     *
     * @param userid the value for userphoto.userid
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userphoto.headphoto
     *
     * @return the value of userphoto.headphoto
     *
     * @mbggenerated
     */
    public String getHeadphoto() {
        return headphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userphoto.headphoto
     *
     * @param headphoto the value for userphoto.headphoto
     *
     * @mbggenerated
     */
    public void setHeadphoto(String headphoto) {
        this.headphoto = headphoto == null ? null : headphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userphoto.headstate
     *
     * @return the value of userphoto.headstate
     *
     * @mbggenerated
     */
    public String getHeadstate() {
        return headstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userphoto.headstate
     *
     * @param headstate the value for userphoto.headstate
     *
     * @mbggenerated
     */
    public void setHeadstate(String headstate) {
        this.headstate = headstate == null ? null : headstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userphoto.idcardphoto
     *
     * @return the value of userphoto.idcardphoto
     *
     * @mbggenerated
     */
    public String getIdcardphoto() {
        return idcardphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userphoto.idcardphoto
     *
     * @param idcardphoto the value for userphoto.idcardphoto
     *
     * @mbggenerated
     */
    public void setIdcardphoto(String idcardphoto) {
        this.idcardphoto = idcardphoto == null ? null : idcardphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userphoto.idcardstate
     *
     * @return the value of userphoto.idcardstate
     *
     * @mbggenerated
     */
    public String getIdcardstate() {
        return idcardstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userphoto.idcardstate
     *
     * @param idcardstate the value for userphoto.idcardstate
     *
     * @mbggenerated
     */
    public void setIdcardstate(String idcardstate) {
        this.idcardstate = idcardstate == null ? null : idcardstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userphoto.stuidcardphoto
     *
     * @return the value of userphoto.stuidcardphoto
     *
     * @mbggenerated
     */
    public String getStuidcardphoto() {
        return stuidcardphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userphoto.stuidcardphoto
     *
     * @param stuidcardphoto the value for userphoto.stuidcardphoto
     *
     * @mbggenerated
     */
    public void setStuidcardphoto(String stuidcardphoto) {
        this.stuidcardphoto = stuidcardphoto == null ? null : stuidcardphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userphoto.stuidcardstate
     *
     * @return the value of userphoto.stuidcardstate
     *
     * @mbggenerated
     */
    public String getStuidcardstate() {
        return stuidcardstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userphoto.stuidcardstate
     *
     * @param stuidcardstate the value for userphoto.stuidcardstate
     *
     * @mbggenerated
     */
    public void setStuidcardstate(String stuidcardstate) {
        this.stuidcardstate = stuidcardstate == null ? null : stuidcardstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userphoto.remark
     *
     * @return the value of userphoto.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userphoto.remark
     *
     * @param remark the value for userphoto.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}